dist: trusty
sudo: false
language: generic

branches:
  only:
    - testing

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libstdc++-5-dev
            - libeigen3-dev
            - libboost-test-dev
      env: COMPILER=gcc CC=gcc-5 CXX=g++-5

script:
  - find /usr/share/cmake*
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
